import type { Metadata } from 'next';
import { Suspense } from 'react';
import Footer from './footer';
import './globals.css';
import { Provider } from './libs/Provider';
import Loading from './loading';
import Navbar from './navbar';

export const metadata: Metadata = {
  title: 'Vending Machine Tracker',
  description: 'Generated by poly-link team',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative flex min-h-screen flex-col pb-28">
        <div className="mb-auto">
          <Navbar />
          <Suspense fallback={<Loading />}>
            {<Provider>{children}</Provider>}
          </Suspense>
          <div className="footer absolute bottom-0 w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
